### ISSUE TITLE
HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by whitas** [moderation/garmin-connect-export#12]
After switching back to master here is still the same issue

```
Traceback (most recent call last):
  File "/Users/tomek/Garmin/garmin-connect-export//gcexport2.py", line 108, in <module>
    hostname_url = http_req('http://connect.garmin.com/gauth/hostname')
  File "/Users/tomek/Garmin/garmin-connect-export//gcexport2.py", line 82, in http_req
    response = opener.open(request, data=post)  # This line may throw a urllib2.HTTPError.
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by moderation** [comment]
@whitas As per the update in [History](https://github.com/moderation/garmin-connect-export#history) the Python 2 `gcexport2.py` version is deprecated and won't work anymore. You need to move to the Python 3 `gcexport3.py`

**Comment by whitas** [comment]
Aahh OK, sorry. My fault, didn't read.
